spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 

mybatis-plus:
  type-aliases-package: com.ysx.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
